multiplier: 100
days_to_expire: 120
donation_prefix: '$'
donation_suffix: ''
thanks_messages:
- Thank you for donating! Here is your reward for today.
- (use /money to see your new balance)
current_donations:
  Notch:
    1: 0
expired_donations:
  Notch:
    0: 0
